// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8AVLFUEREuGe3OjtoEXo1YBesyCY5FeU',
    appId: '1:286832426144:web:da696336df2f97fca5ddc5',
    messagingSenderId: '286832426144',
    projectId: 'election-9557c',
    authDomain: 'election-9557c.firebaseapp.com',
    storageBucket: 'election-9557c.appspot.com',
    measurementId: 'G-QZCF4KE53J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0HLGvwYienHYHCXgO6zt3ANMA2Pj6GmI',
    appId: '1:286832426144:android:7730da626a133c1ca5ddc5',
    messagingSenderId: '286832426144',
    projectId: 'election-9557c',
    storageBucket: 'election-9557c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDra09VVvLeQHGSJb6o9DPrwiYF4Mv7krg',
    appId: '1:286832426144:ios:4525937d095d4384a5ddc5',
    messagingSenderId: '286832426144',
    projectId: 'election-9557c',
    storageBucket: 'election-9557c.appspot.com',
    iosClientId: '286832426144-miip1dfr94i1qn061r2tp2u9rq1gon3l.apps.googleusercontent.com',
    iosBundleId: 'com.example.election',
  );
}
